"""init_schema

Revision ID: cd0f621d3632
Revises: 
Create Date: 2026-07-18 20:38:04.462782
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision = 'cd0f621d3632'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_id', sa.BigInteger(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('reply_to', sa.BigInteger(), nullable=True, comment='引用消息id'),
    sa.Column('bot', sa.Boolean(), nullable=False, comment='True=agent自动回复'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['work_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_messages_created_at'), 'group_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_group_messages_group_id'), 'group_messages', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_messages_user_id'), 'group_messages', ['user_id'], unique=False)
    op.alter_column('documents', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='原始文件名',
               existing_nullable=False)
    op.alter_column('documents', 'display_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False,
               comment='显示名称(可改)',
               existing_server_default=sa.text("''"))
    op.alter_column('knowledge_bases', 'splitter_regex',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=False,
               comment='regex 分块时的分隔正则',
               existing_server_default=sa.text("''"))
    op.alter_column('knowledge_bases', 'loader',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=False,
               comment='加载器: text/pdf/docx/markdown/image...',
               existing_server_default=sa.text("'text'"))
    op.alter_column('knowledge_bases', 'icon_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               nullable=False,
               comment='知识库图标URL',
               existing_server_default=sa.text("''"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_bases', 'icon_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               nullable=True,
               comment=None,
               existing_comment='知识库图标URL',
               existing_server_default=sa.text("''"))
    op.alter_column('knowledge_bases', 'loader',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32),
               nullable=True,
               comment=None,
               existing_comment='加载器: text/pdf/docx/markdown/image...',
               existing_server_default=sa.text("'text'"))
    op.alter_column('knowledge_bases', 'splitter_regex',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=True,
               comment=None,
               existing_comment='regex 分块时的分隔正则',
               existing_server_default=sa.text("''"))
    op.alter_column('documents', 'display_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True,
               comment=None,
               existing_comment='显示名称(可改)',
               existing_server_default=sa.text("''"))
    op.alter_column('documents', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment=None,
               existing_comment='原始文件名',
               existing_nullable=False)
    op.drop_index(op.f('ix_group_messages_user_id'), table_name='group_messages')
    op.drop_index(op.f('ix_group_messages_group_id'), table_name='group_messages')
    op.drop_index(op.f('ix_group_messages_created_at'), table_name='group_messages')
    op.drop_table('group_messages')
    # ### end Alembic commands ###
